name: CD to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        pip install huggingface_hub
        huggingface-cli login --token "${{ secrets.HF_TOKEN }}"
        # Add commands to push your model or dataset to Hugging Face
        # For example:
        # huggingface-cli repo create <repo_name>
        # huggingface-cli upload <path_to_files> --repo_id <repo_id>
