name: Documentation Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install mkdocs mkdocs-material
    - name: Deploy Documentation
      run: |
        source venv/bin/activate
        mkdocs gh-deploy --force